### ISSUE TITLE
Bash

### ISSUE THREAD

**Issue by jasperes** [ArezzoCo-Tech-Talk/talks#1]
Apresentação Parte 1: https://www.youtube.com/watch?v=yIAISt7jln0

- about (shells)
- stdin(0), stdout(1), stderr(2)
- exit code (success=0, failure=1...255)
- redirect (>, >>, 1>, 2>, &>)
- pipe ( | )
- subprocess (cmd)
- condition (&&, ||)

**Comment by andressltz** [comment]
Jonathan apresentou no dia 30/07/2021

**Comment by andressltz** [comment]
@jasperes apresentou a parte 2 no dia 13/08/2021
