### ISSUE TITLE
WSL (Windows subsystem Linux) - Linux para quem não quer deixar o Windows

### ISSUE THREAD

**Issue by RigottiG** [ArezzoCo-Tech-Talk/talks#28]
- Windows vs Linux
- WSL 1
- WSL 2
- Hybris no WSL 2
- GUI

**Comment by andressltz** [comment]
Apresentado pelo @andressltz no dia 27/08/2021.

**Comment by andressltz** [comment]
**Links**

Apresentação: https://youtu.be/zo42VGIUzAo

Documentação da Microsoft:
- https://docs.microsoft.com/pt-br/windows/wsl/compare-versions
- https://code.visualstudio.com/blogs/2020/03/02/docker-in-wsl2
- [Instalação] https://docs.microsoft.com/pt-br/windows/wsl/install-win10

Documentação sobre WSLg (lançamento público previsto para Outubro/2021):
- https://devblogs.microsoft.com/commandline/wslg-architecture/
- https://docs.microsoft.com/pt-br/windows/wsl/tutorials/gui-apps

Tutoriais para instalação:
- [Inglês] https://maurogiusti.medium.com/running-ubuntu-on-windows-10-with-wsl2-c4f06b3c353
- [Inglês] https://maurogiusti.medium.com/running-ubuntu-on-windows-10-with-wsl2-part-2-windows-terminal-bdcad3328cfd
- [Inglês] https://medium.com/@japheth.yates/the-complete-wsl2-gui-setup-2582828f4577
- [Português] https://medium.com/@lucasoaresgomes/ambiente-de-desenvolvimento-no-windows-wsl2-ubuntu-20-04-terminal-zsh-8cef0d2c0cc1
- [Português] https://marquesfernandes.com/desenvolvimento/como-desenvolver-com-docker-no-linux-dentro-do-windows-sem-dual-boot-wsl-2/
