### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ghost** [ArezzoCo-Tech-Talk/talks#47]
Um papo sobre code review: 
- O que devemos observar? 
- Qual a melhor forma de fazer os comentários? 
- Tamanho de PR é um problema?

**Comment by andressltz** [comment]
TECHTALK DA SEMANA
Data: 16/07 - 11h
Onde: Call será puxada no #general do slack
Assunto: Code Review
Autor: @emilioheinz

**Comment by andressltz** [comment]
Realizada pelo @emilioheinz no dia 16/07/2021.
