### ISSUE TITLE
Testes no React utilizando a Testing Library

### ISSUE THREAD

**Issue by andressltz** [ArezzoCo-Tech-Talk/talks#48]
Testes no React utilizando a Testing Library Será apresentada no dia 09/07/2021 pelo @RigottiG .

**Comment by RigottiG** [comment]
Segue os links:
https://youtu.be/1VN60K4b7IU

https://drive.google.com/file/d/1uM896tcSjPKiOHB6I1Iycb0gpDiRN1Cr/view?usp=sharing

E segue também o post com boas práticas para o uso da Testing Library escritas pelo criador (lá ele comenta sobre usar o screen e nao direto do render e etc..)

https://kentcdodds.com/blog/common-mistakes-with-react-testing-library
